spring:
  profiles:
    active: dev
  application:
    name: ehr-communication
  redis:
    host: 127.0.0.1
    password: 171224
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000

server:
  port: 8083
  eureka:
    port: 8761

eureka:
  instance:
    ip-address: 10.23.15.4
    hostname: ${eureka.instance.ip-address}
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.eureka.port}/eureka/

spring:
  

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
