spring:
  profiles:
    active: dev
  application:
    name: ehr-file
server:
  port: 8084
  eureka:
    port: 8761

eureka:
  instance:
    ip-address: localhost
    hostname: ${eureka.instance.ip-address}
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.eureka.port}/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  resHost: 10.23.15.18
  storagePort: 8001
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 10.23.15.18:22122